Add test tsconfig
Suppresses error TS151001 from tsc via ts-jest (despite having disabled diagnostics).

esbuild-jest isn't currently viable as it breaks coverage reporting.